import express from "express";
import path from "path";
import dotenv from "dotenv";
import { GoogleGenAI, Type } from "@google/genai";
import { createServer as createViteServer } from "vite";

// Load environment variables
dotenv.config();

const PORT = 3000;

// Initialize Google Gen AI client with User-Agent for telemetry
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

async function startServer() {
  const app = express();

  // Configure body parsers with limits for processing raw base64 images
  app.use(express.json({ limit: "15mb" }));
  app.use(express.urlencoded({ limit: "15mb", extended: true }));

  // API Route to analyze base64 image and ghostwrite a story
  app.post("/api/analyze", async (req, res) => {
    try {
      const { image, mimeType, userNotes } = req.body;

      if (!image) {
        return res.status(400).json({ error: "No image data supplied." });
      }

      // Prepare image parts for Gemini
      const imagePart = {
        inlineData: {
          mimeType: mimeType || "image/jpeg",
          data: image,
        },
      };

      // Instruct the AI to do a dual-pass evaluation:
      // First, extract literal text so the client can display exactly what is natively in the source.
      // Second, do a moody visual analysis and draft a polished opening paragraph.
      const promptText = `
        Perform a strict, safe, and factual analysis of the uploaded image to support the creative ghostwriting application.
        
        Follow this strict process:
        1. Parse the image for any literal, readable text (handwriting, signage, page text, labels, watermarks, etc.). Extract exactly what is written Word-for-Word. This is crucial for transparency to show what is factual. If no text exists, state exactly: "No text physically written in the image."
        2. Analyze the atmospheric setting, mood (e.g. moody cyan, dark romanticism, cyberpunk retro, optimistic pastoral), objects, and characters.
        3. Compose a gorgeous, highly expressive opening story paragraph of 100-150 words set directly inside this visual universe, incorporating optional user-supplied keywords or themes if provided.
        
        ${userNotes ? `User writing direction/themes to incorporate: "${userNotes}"` : ""}
      `;

      const textPart = {
        text: promptText,
      };

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: { parts: [imagePart, textPart] },
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              extractedText: {
                type: Type.STRING,
                description: "Extract all visible literal text, letters, handwriting, or typography written physically within the image. Be extremely literal and word-for-word. If absolutely none are found, say: 'No text physically written in the image.'"
              },
              visualSummary: {
                type: Type.STRING,
                description: "Describe the setting, lighting, characters, and overall mood of the image."
              },
              settingMood: {
                type: Type.STRING,
                description: "One word or short phrase representing the key mood (e.g. Nostalgic, Cyberpunk, Cinematic, Somber, Peaceful)."
              },
              ghostwrittenParagraph: {
                type: Type.STRING,
                description: "A highly creative, atmospheric, and professionally crafted opening paragraph of a story or novel (100 to 150 words) set in this scene. Make it immersive."
              }
            },
            required: ["extractedText", "visualSummary", "settingMood", "ghostwrittenParagraph"]
          }
        }
      });

      // Parse the JSON string from Gemini response
      if (!response.text) {
        throw new Error("No response content generated by the AI model.");
      }

      const responseJson = JSON.parse(response.text.trim());
      return res.json(responseJson);

    } catch (error: any) {
      console.error("Error analyzing image:", error);
      return res.status(500).json({
        error: error.message || "An error occurred during Gemini evaluation.",
      });
    }
  });

  // Vite integration
  if (process.env.NODE_ENV !== "production") {
    console.log("Starting server in development mode with Vite HMR middleware...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting server in production mode...");
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Express custom server listening at http://0.0.0.0:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("Failed to start custom express server:", err);
});
